apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    events {
    worker_connections 1024;
    }
    
    http {
          upstream backend {
            server app-1-svc:8080;
            server app-2-svc:8080;
          }

          server {
            listen 8080;

            location / {
              proxy_pass http://backend;
            }
          }
        }